#!/usr/bin/env bash
# # Configure Nginx server so that /redirect_me is redirecting to another page
# redirection must be a “301 Moved Permanently”

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
# configure /redirect_me to redirect to another page and “301 Moved Permanently”
new="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/youtube.com\/@100bunco;\n\t}"
sudo sed -i "s/server_name _;/$new/" /etc/nginx/sites-available/default
#restart nginx
sudo service nginx restart
