#!/usr/bin/env bash
# script that install and configures haproxy

sudo apt-get upadate
sudo apt-get install -y haproxy

echo \
"
frontend my_frontend
	bind *:80
	mode http
	default_backend my_backend
backend my_backend
	mode http
	balance roundrobin
	server 427026-web-01 54.236.24.191
	server 427026-web-02 35.175.126.34" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
